package com.zenyte.game.world.entity.player.action.combat;


import static com.zenyte.game.item.ids.ItemId.*;

public final class BowItemIds {

	public static final int[] CRYSTAL_BOW_ITEM_IDS = new int[]{
			NEW_CRYSTAL_BOW, CRYSTAL_BOW_FULL, CRYSTAL_BOW_910, CRYSTAL_BOW_810, CRYSTAL_BOW_710, CRYSTAL_BOW_610,
            CRYSTAL_BOW_510, CRYSTAL_BOW_410, CRYSTAL_BOW_310, CRYSTAL_BOW_210, CRYSTAL_BOW_110,
            NEW_CRYSTAL_BOW_I, CRYSTAL_BOW_FULL_I, CRYSTAL_BOW_910_I, CRYSTAL_BOW_810_I, CRYSTAL_BOW_710_I, CRYSTAL_BOW_610_I,
            CRYSTAL_BOW_510_I, CRYSTAL_BOW_410_I, CRYSTAL_BOW_310_I, CRYSTAL_BOW_210_I, CRYSTAL_BOW_110_I,

			CRYSTAL_BOW_BASIC, CRYSTAL_BOW_ATTUNED, CRYSTAL_BOW_PERFECTED,
			CORRUPTED_BOW_BASIC, CORRUPTED_BOW_ATTUNED, CORRUPTED_BOW_PERFECTED,

            CRYSTAL_BOW, CRYSTAL_BOW_INACTIVE,
            BOW_OF_FAERDHINEN,
            BOW_OF_FAERDHINEN_INACTIVE,
			BOW_OF_FAERDHINEN_C,
			BOW_OF_FAERDHINEN_C_25884,
			BOW_OF_FAERDHINEN_C_25886,
			BOW_OF_FAERDHINEN_C_25888,
			BOW_OF_FAERDHINEN_C_25890,
			BOW_OF_FAERDHINEN_C_25892,
			BOW_OF_FAERDHINEN_C_25894,
			BOW_OF_FAERDHINEN_C_25896
	};

}
